#test
key = "TACACS-KEY"

accounting file = /var/log/tac_plus.acct

group = admins {
        default service = permit

        service = exec {
                priv-lvl = 15
        }
}


user = admin {
        member = admins
        login = cleartext "cisco"
}