key="TACACS-KEY"

group = admin {
        default service = permit
        service = exec {
                priv-lvl = 15
                shell:roles="\"nettverks-admin\""
        }
}

group = operator {
        default service = permit
        service = exec {
                priv-lvl = 1
                shell:roles="\"nettverks-operatør\""
        }
}

user = lan-admin {
        member = admin
        login = cleartext bani
}

user = lan-operator {
        member = operator
        login = cleartext bani
}